<?php
$inputformhtml = "";
$inputformhtml = $inputformhtml . '<div class="item">';
$inputformhtml = $inputformhtml . '<p>Use this form to generate all sequences for a library.</p>';
$inputformhtml = $inputformhtml . '<p>If you are inserting a DNA sequence, please only use DNA nucleotide letters (<b>a</b>, <b>c</b>, <b>g</b> and <b>t</b>) or <a href="degenerate.htm">degenerate nucleotides</a>. The algorithm will translate the sequence and work out the library options at each position automatically.</p>';
$inputformhtml = $inputformhtml . '<p>If you are inserting an amino acid sequence, use only single letter amino acid codes, or ? where you want to place randomised positions within the amino acid positions.</p>';
$inputformhtml = $inputformhtml . '<p>To add library options, use the "Options" box, add options for 1 position per line, and use single letter amino acid codes for the amino acid options each position. The algorithm will add these residues to positions in the sequence which are specified with ?s.</p><p>Alternatively, if you are specifying all possible options at that position, you may instead insert * into the options box for that line. You can also specify all but certain residues by using the format "*-" with the residues you do not want following.</p>';
$inputformhtml = $inputformhtml . '<p>The maximum number of sequences that will be generated by this script is ' . $maximumsequences . ', unless you opt for downstream processing, which you will be prompted for on the following page.</p>';
$inputformhtml = $inputformhtml . '<form action="?page=LibraryGenerator" method="post">';
$inputformhtml = $inputformhtml . '<table>';
$inputformhtml = $inputformhtml . '<tr>';
$inputformhtml = $inputformhtml . '<td><p>Input Type:</p></td>';
$inputformhtml = $inputformhtml . '<td><select name="Input"><option selected>Protein<option>DNA</select></td>';
$inputformhtml = $inputformhtml . '</tr>';
$inputformhtml = $inputformhtml . '<tr>';
$inputformhtml = $inputformhtml . '<td><p>Sequence:</p></td>';
$inputformhtml = $inputformhtml . '<td><input type="text" name="Sequence" size="40"></td>';
$inputformhtml = $inputformhtml . '</tr>';
$inputformhtml = $inputformhtml . '<tr>';
$inputformhtml = $inputformhtml . '<td><p>Options:</p></td>';
$inputformhtml = $inputformhtml . '<td><textarea name="Randoms" cols="20" rows="5"></textarea></td>';
$inputformhtml = $inputformhtml . '</tr>';
$inputformhtml = $inputformhtml . '</table>';
$inputformhtml = $inputformhtml . '<p><input type="submit" name="Submit" value="Submit"><input type="reset" value="Reset"></p>';
$inputformhtml = $inputformhtml . '</form>';
$inputformhtml = $inputformhtml . '</div>'
?>
